# Generated by Django 5.0.2 on 2024-02-13 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, null=True, verbose_name='Texto de la Pregunta')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions', verbose_name='Imagen de la pregunta')),
                ('answer1', models.CharField(max_length=200, verbose_name='Pregunta A')),
                ('answer2', models.CharField(max_length=200, verbose_name='Pregunta B')),
                ('answer3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pregunta C')),
                ('answer4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pregunta D')),
                ('correct', models.CharField(max_length=5, verbose_name='Respuesta Pregunta')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librery.module', verbose_name='Modulo')),
            ],
        ),
    ]
